### ISSUE TITLE
interrupted replace when term is not found

### ISSUE THREAD

**Issue by michael-mhrdd** [tana-gh/vector-replace#6]
The extension stops replacing subsequent terms when a search term is not found:

![2021-05-30 21 54 44](https://user-images.githubusercontent.com/32603540/120118197-af46bf00-c191-11eb-87f9-9f4eb97de7aa.png)

- a and be are replaced as expected
- c does not occur in the text, i.e. it is not found.
- d and e are left unchanged, even though they do occur in the text.

Is it possible to have the extension skip/ignore search terms that are not found and continue to replace subsequent search terms?

**Comment by tana-gh** [comment]
Thank you for your nice issue.
I considered this problem during development, but at the time I gave up on including it in the specification.
Let's reconsider here.

Consider the following search strings:
```
a
b
c
d
e
```

When the following editor text, it will be like this...
```
a  # matched
b  # matched
d  # c is skipped, and d is matched
e  # matched
```

Then, what should we do in this case?
```
a  # matched
b  # matched
e  # c and d are skipped...? (1)
d  # c is skipped, and d is matched...? (2)
```

In this case, the uncertain choices of (1) and (2) remain.
To determine this, additional policies are required.

Additional policies:
(A)
In order to allow (1), adopt next string with the shortest distance from the current match to the next match.
(B)
In order to allow (2), adopt next search with the closest to the current search string.

Problems:
(A) has the following problems:
- If a string near the end of search strings match the beginning of the editor text, there is a problem that many of the search strings are skipped.
- If loop search is enabled, there will be no search order completely.
- When the search strings are 'b, abc' for example, the way of matching the text 'abc' remains ambiguous, and requires additional policy.

(B) has the following problems:
- The behavior when the match succeeds and fails becomes asymmetric. That is, if there is a match for the current search string at near the end of the editor text, it will always match, and many subsequent search strings will be unmatched. However, if there is no search string behind the current position, only the current search string will be skipped, and possibility to match will be remained for many subsequent search strings.

What I think is, (B) is more suitable, but I was worried about that, so I forgot to solve this problem during first development.

Please let me ​know if you have any thoughts or requests about this.

**Comment by michael-mhrdd** [comment]
Thank you for your kind reply. I did not quite realize the complexity of the problem. The solution for notepad++ shown [here ](https://stackoverflow.com/questions/11389466/multiple-word-search-and-replace-in-notepad) works well for my purposes, but I am not sure which of your options (A) or (B) it corresponds to.

**Comment by tana-gh** [comment]
I was convinced by seeing the example of notepad++.
I valued the order of the search strings, but it seems convenient to implement a search that ignores the order, and it seems that your request can be solved.
I will implement it immediately.
This functionality will be as a new setting option.
Thank you for your issue!

**Comment by tana-gh** [comment]
Sorry, I said I would implement, but since there is a problem that the search may become heavy, I put on hold this feature.

**Comment by michael-mhrdd** [comment]
No problem. I appreciate that you looked into it. Thanks!

**Comment by tana-gh** [comment]
New search option, "Matrix search", that ignores the order has been implemented.
This feature will be enabled in the next version 2.0.0.

But performance problem still remains.
This problem has been isolated another issue.

-> Bad performance #12

This issue is now successfully closed.
Thank you.

**Comment by gcem** [comment]
This feature has an important use case. With it, we can use this extension for swapping two words. That is, we can simultaneously change A's to B's, and B's to A's. Matrix search option does this perfectly. Thank you for implementing it.
